server:
  port: 8085
spring:
  application:
    name: softai
  ai:
    # MCP 服务
    mcp:
      server:
        protocol: STREAMABLE # STREAMABLE STATELESS
        name: softai-mcp  # 服务器名称
        version: 1.0.0
        toolcallback-enabled: true
        streamable-http:
          mcp-endpoint: /mcp  #默认是mcp
          keep-alive-interval: 60s
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.lazuream.ai: debug